### PR TITLE
Implement go-gitea/gitea#1107 and go-gitea/gitea#815

### PR DESCRIPTION
**Pull request by sapk**
fixes for building bolt on mips platforms.

### CODE REVIEW

**Comment by tboerger** [comment]
Do you know if these values are really correct? I can't find a source for proper trustable values.

**Comment by sapk** [comment]
I simply use those that were used in gitea. 
@lunny, for mips/mipsle, use a PR on bolt boltdb/bolt#663 (not merged)

**Comment by sapk** [comment]
This is simply to don't have custom modification from vendor in gitea and be able to check in drone if any correction needs to be done (add or remove) or if someone modified them.

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
